In [36]:
import os
import numpy as np
import pandas as pd

In [37]:
# Load the datasets
file_path_1 = '../../Datasets/Supervised Learning Inputs/MLInput_ATP_TI_cleaned_supervised.csv'  # Replace with your file path
file_path_2 = '../../Datasets/Supervised Learning Inputs/MCAS_AADP.csv'  # Replace with your file path

data1 = pd.read_csv(file_path_1, encoding = "cp1252")
data2 = pd.read_csv(file_path_2, encoding = "cp1252")

data1['UPN'] = data1['UPN'].str.split('@').str[0]

In [38]:
# Merge the datasets
merged_data = pd.merge(data1, data2, on='UPN', how='outer')
merged_data

,Unnamed: 0_x,UPN,AvgProbability_x,UPN Count_x,Brand impersonation,Malicious URL reputation,Malware,Threats,Unnamed: 0_y,Delete messages from Deleted Items folder,Failed log on,Suspicious Email,UPN Count_y,Threat Count,AvgProbability_y
0,0.0,Account,0.7333,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,Maerskshipping,0.7423,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,abby,0.7355,2.0,0.0,0.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,abhinaya.sathyanarayanan,NaN,NaN,NaN,NaN,NaN,NaN,0.0,4.0,0.0,0.0,4.0,4.0,0.7168
4,3.0,aditya.sahasrabudhe,0.7947,4.0,0.0,0.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,NaN,yogeshchaughule,NaN,NaN,NaN,NaN,NaN,NaN,174.0,1.0,1.0,0.0,2.0,2.0,0.8145
431,292.0,yuvaraj.narayanaswamy,0.8575,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,NaN,yuvaraj.rajendran,NaN,NaN,NaN,NaN,NaN,NaN,175.0,2.0,0.0,0.0,2.0,2.0,0.8142
433,293.0,yuvaraja.kumar,0.7267,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
434,NaN,yuvarajan.paneerselvam,NaN,NaN,NaN,NaN,NaN,NaN,176.0,1.0,0.0,0.0,1.0,1.0,0.7848

In [39]:
# Fill missing columns with 0
merged_data = merged_data.fillna(0)

def calculate_avg_probability(row):
    if row['AvgProbability_x'] == 0:
        return row['AvgProbability_y']
    elif row['AvgProbability_y'] == 0:
        return row['AvgProbability_x']
    else:
        return (row['AvgProbability_x'] + row['AvgProbability_y']) / 2

merged_data['AvgProbability'] = merged_data.apply(calculate_avg_probability, axis=1)
merged_data['UPN Count'] = merged_data['UPN Count_x'] + merged_data['UPN Count_y']
merged_data = merged_data.drop(columns=['AvgProbability_x', 'AvgProbability_y','UPN Count_x','UPN Count_y'])

# Save the merged dataset
merged_file_path = '../../Datasets/Supervised Learning Inputs/ATP_TI_MCAS_AADP.csv'  # Replace with your desired output path
merged_data['AvgProbability'] = merged_data['AvgProbability'].round(4)
merged_data.to_csv(merged_file_path, index=False)